pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r ./* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

deploy_aws_s3_node:
  stage: deploy
  image: 696577169457.dkr.ecr.eu-central-1.amazonaws.com/baseimages/node:14.15.4
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install -i $HOME -b $HOME/bin
    - npm i -g @sbks/maratonec-cli gulp-cli
    - npm install gulp gulp-imagemin gulp-concat gulp-terser gulp-change gulp-sourcemaps
    - gulp
    - smrt env save production
    - source .env
    - $HOME/bin/aws s3 cp ./ s3://sbks-misc/misc-cdn/misc/api-connectors/tableau-connector --exclude "*" --include "socialbakers_wdc_api.html" --include "all.js" --include "all.js.map" --include "images/*" --recursive --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate
  only:
    - master
